pipeline_config_id: plrunner_config


data_config :
  data_format: json
  train_dir:  easytpp/taxi  # ./data/taxi/train.json
  valid_dir:  easytpp/taxi # ./data/taxi/dev.json
  test_dir:  easytpp/taxi # ./data/taxi/test.json
  tokenizer_config:
    pad_token_id: 10
    padding_side: right
    padding_strategy: longest
  specs :
    batch_size : 256
    num_event_types: 10
model_config:
  model_id : NHP
  hidden_size : 64
  loss_integral_num_sample_per_step: 20
  thinning:
    num_seq: 10
    num_sample: 1
    num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
    look_ahead_time: 10
    patience_counter: 5 # the maximum iteration used in adaptive thinning
    over_sample_rate: 5
    num_samples_boundary: 5
    dtime_max: 5
    num_step_gen: 1
trainer_config : 
  max_epochs : 200
  val_freq : 5
  lr : 0.01
  lr_scheduler : True
  save_model_dir : ./trained_model
  logger_type : wandb
  logger_config : 
    project : train_test
    name : test
    save_dir : ./wandblogger_test