pipeline_config_id : syn_gen_config

H1exp : 
  model_id : Hawkes
  save_dir : ./data
  num_mark : 1
  start_time : 0
  end_time : 20
  test_end_time : 25
  num_batch : 5
  batch_size : 2
  sampler_config :
    num_samples : 30
    num_exp : 100
    num_samples_boundary : 30
    over_sample_rate : 1
    dtime_max : 2
    patience_counter : 100
  model_config : 
    mu : 0.3
    alpha : 0.65
    decay : 0.8

