# ===== DATA CONFIGURATIONS =====

taxi:
  data_format: json
  train_dir: new_ltpp/taxi
  valid_dir: new_ltpp/taxi
  test_dir: new_ltpp/taxi
  tokenizer_specs:
    num_event_types: 10
    pad_token_id: 10
    padding_side: left
 
taobao:
  data_format: json
  train_dir: new_ltpp/taobao
  valid_dir: new_ltpp/taobao
  test_dir: new_ltpp/taobao
  tokenizer_specs:
    num_event_types: 17
    pad_token_id: 17
    padding_side: left

amazon:
  data_format: json
  train_dir: new_ltpp/amazon
  valid_dir: new_ltpp/amazon
  test_dir: new_ltpp/amazon
  tokenizer_specs:
    num_event_types: 16
    pad_token_id: 16
    padding_side: left

test:
  data_format: json
  train_dir: NzoCs/test_dataset
  valid_dir: NzoCs/test_dataset
  test_dir: NzoCs/test_dataset
  tokenizer_specs:
    num_event_types: 2
    pad_token_id: 2
    padding_side: left
    
hawkes1:
  data_format: json
  train_dir: NzoCs/hawkes1
  valid_dir: NzoCs/hawkes1
  test_dir: NzoCs/hawkes1
  tokenizer_specs:
    num_event_types: 1
    pad_token_id: 1
    padding_side: left

hawkes2:
  data_format: json
  train_dir: NzoCs/hawkes2
  valid_dir: NzoCs/hawkes2
  test_dir: NzoCs/hawkes2
  tokenizer_specs:
    num_event_types: 2
    pad_token_id: 2
    padding_side: left