# ===== MODEL CONFIGURATIONS =====
# Configurations for model-specific parameters (architecture, hyperparameters, etc.)

# Common base configuration
base_config:
  lr: 0.001
  lr_scheduler: True

# Configurations for neural models - Size Small
neural_small:
  specs:
    hidden_size: 16
    time_emb_size: 8
    num_layers: 1
  num_heads: 2  # For attention-based models

# Configurations for neural models - Size Medium
neural_medium:
  specs:
    hidden_size: 32
    time_emb_size: 16
    num_layers: 2
  num_heads: 4  # For attention-based models

# Configurations for neural models - Size Large
neural_large:
  specs:
    hidden_size: 64
    time_emb_size: 32
    num_layers: 3
  num_heads: 8  # For attention-based models

# Configurations for neural models - Size Extra Large
neural_xlarge:
  specs:
    hidden_size: 128
    time_emb_size: 64
    num_layers: 4
  num_heads: 16  # For attention-based models

# Specific configurations for Hawkes - Simple (univariate)
hawkes_simple:
  specs:
    mu: 0.2
    alpha: 0.8
    beta: 1.0

# Specific configurations for Hawkes - Bivariate
hawkes_bivariate:
  specs:
    mu: [0.2, 0.2]
    alpha: [[0.4, 0], [0, 0.8]]
    beta: [[1.0, 0], [0, 1.0]]

# Specific configurations for Hawkes - Complex multivariate
hawkes_multivariate:
  specs:
    mu: [0.2, 0.2, 0.1]
    alpha: [[0.4, 0.1, 0], [0.1, 0.8, 0.2], [0, 0.2, 0.6]]
    beta: [[1.0, 0.5, 0], [0.5, 1.0, 0.8], [0, 0.8, 1.0]]

# Configurations for FullyNN - More samples in thinning
fullyNN_enhanced:
  specs:
    hidden_size: 32
    time_emb_size: 16
    num_layers: 2

