# ===== CONFIGURATIONS DE SIMULATION ET THINNING =====

# Configuration de thinning rapide (pour tests)
thinning_fast:
  num_exp: 50
  over_sample_rate: 1.2
  dtime_max: 3
  num_sample: 15

# Configuration de thinning standard  
thinning_standard:
  num_exp: 100
  over_sample_rate: 1.5
  dtime_max: 5
  num_sample: 30

# Configuration de thinning haute qualité
thinning_high_quality:
  num_exp: 150
  over_sample_rate: 1.8
  dtime_max: 8
  num_sample: 50

# Configuration de thinning pour gros datasets
thinning_large_dataset:
  num_exp: 200
  over_sample_rate: 2.0
  dtime_max: 10
  num_sample: 60

# Configuration de thinning pour FullyNN (plus d'échantillons)
thinning_fullyNN:
  num_exp: 200
  over_sample_rate: 1.5
  dtime_max: 5
  num_sample: 60

# Configuration de thinning minimale (debug/CPU)
thinning_minimal:
  num_exp: 20
  over_sample_rate: 1.1
  dtime_max: 2
  num_sample: 10

# Configuration de simulation rapide (tests)
simulation_fast:
  start_time: 20
  end_time: 50
  max_sim_events: 5000

# Configuration de simulation développement
simulation_dev:
  start_time: 50
  end_time: 120
  max_sim_events: 15000

# Configuration de simulation standard
simulation_standard:
  start_time: 100
  end_time: 200
  max_sim_events: 50000

# Configuration de simulation étendue
simulation_extended:
  start_time: 100
  end_time: 300
  max_sim_events: 100000

# Configuration de simulation pour gros datasets
simulation_large:
  start_time: 100
  end_time: 400
  max_sim_events: 150000

# Configuration de simulation pour validation croisée
simulation_cv:
  start_time: 80
  end_time: 160
  max_sim_events: 30000

# Configuration de simulation pour expérimentations
simulation_experiment:
  start_time: 50
  end_time: 120
  max_sim_events: 15000