# ===== SIMULATION AND THINNING CONFIGURATIONS =====

# Fast thinning configuration (for tests)
thinning_fast:
  num_exp: 50
  over_sample_rate: 1.2
  dtime_max: 3
  num_sample: 15

# Standard thinning configuration
thinning_standard:
  num_exp: 100
  over_sample_rate: 1.5
  dtime_max: 5
  num_sample: 30

# High-quality thinning configuration
thinning_high_quality:
  num_exp: 150
  over_sample_rate: 1.8
  dtime_max: 8
  num_sample: 50

# Thinning configuration for large datasets
thinning_large_dataset:
  num_exp: 200
  over_sample_rate: 2.0
  dtime_max: 10
  num_sample: 60

# Thinning configuration for FullyNN (more samples)
thinning_fullyNN:
  num_exp: 200
  over_sample_rate: 1.5
  dtime_max: 5
  num_sample: 60

# Minimal thinning configuration (debug/CPU)
thinning_minimal:
  num_exp: 20
  over_sample_rate: 1.1
  dtime_max: 2
  num_sample: 10

# Fast simulation configuration (tests)
simulation_fast:
  start_time: 20
  end_time: 50
  max_sim_events: 5000

# Development simulation configuration
simulation_dev:
  start_time: 50
  end_time: 120
  max_sim_events: 15000

# Standard simulation configuration
simulation_standard:
  start_time: 100
  end_time: 200
  max_sim_events: 50000

# Extended simulation configuration
simulation_extended:
  start_time: 100
  end_time: 300
  max_sim_events: 100000

# Simulation configuration for large datasets
simulation_large:
  start_time: 100
  end_time: 400
  max_sim_events: 150000

# Simulation configuration for cross-validation
simulation_cv:
  start_time: 80
  end_time: 160
  max_sim_events: 30000

# Simulation configuration for experiments
simulation_experiment:
  start_time: 50
  end_time: 120
  max_sim_events: 15000