pipeline_config_id: runner_config

data:

  taxi:
    data_format: json
    train_dir: easytpp/taxi
    valid_dir: easytpp/taxi
    test_dir: easytpp/taxi
    data_specs:
      num_event_types: 10
      pad_token_id: 10
      padding_side: left

  test:
    data_format: json
    train_dir: NzoCs/test-temporal-dataset
    valid_dir: NzoCs/test-temporal-dataset
    test_dir: NzoCs/test-temporal-dataset
    data_specs:
      num_event_types: 2
      pad_token_id: 2
      padding_side: left
      
  H2expi:
    data_format: json
    train_dir: NzoCs/H2expi-temporal-dataset
    valid_dir: NzoCs/H2expi-temporal-dataset
    test_dir: NzoCs/H2expi-temporal-dataset
    data_specs:
      num_event_types: 2
      pad_token_id: 2
      padding_side: left

  H2expc:
    data_format: json
    train_dir: NzoCs/H2expc-temporal-dataset
    valid_dir: NzoCs/H2expc-temporal-dataset
    test_dir: NzoCs/H2expc-temporal-dataset
    data_specs:
      num_event_types: 2
      pad_token_id: 2
      padding_side: left

  hawkes1:
    data_format: json
    train_dir: NzoCs/hawkes1-temporal-dataset
    valid_dir: NzoCs/hawkes1-temporal-dataset
    test_dir: NzoCs/hawkes1-temporal-dataset
    data_specs:
      num_event_types: 1
      pad_token_id: 1
      padding_side: left

  hawkes2:
    data_format: json
    train_dir: NzoCs/hawkes2_-temporal-dataset
    valid_dir: NzoCs/hawkes2_-temporal-dataset
    test_dir: NzoCs/hawkes2_-temporal-dataset
    data_specs:
      num_event_types: 2
      pad_token_id: 2
      padding_side: left

  self_correcting:
    data_format: json
    train_dir: NzoCs/self_correcting-temporal-dataset
    valid_dir: NzoCs/self_correcting-temporal-dataset
    test_dir: NzoCs/self_correcting-temporal-dataset
    data_specs:
      num_event_types: 1
      pad_token_id: 1
      padding_side: left

checkpoints_dir: checkpoints

test :
  data_loading_specs:
    batch_size: 32
    num_workers: 1
    
  model_config:
    model_id: HawkesModel
    specs:
      mu: [0.2, 0.2]
      alpha: [[0.4, 0], [0, 8.0]]
      beta: [[1.0, 0], [0, 20.0]]
    thinning:
      num_exp: 200
      num_sample: 100
      over_sample_rate: 1.5
      dtime_max: 5

  trainer_config:
    stage: test

hawkes1 :
  data_loading_specs:
    batch_size: 128
    num_workers: 1
    
  model_config:
    model_id: HawkesModel
    specs:
      mu: 0.2
      alpha: 0.8
      beta: 1
    thinning:
      num_exp: 500
      num_sample: 100
      over_sample_rate: 1.5
      dtime_max: 5

  trainer_config:
    stage: test

hawkes2 :
  data_loading_specs:
    batch_size: 128
    num_workers: 1
    
  model_config:
    model_id: HawkesModel
    specs:
      mu: [0.2, 0.2]
      alpha: [[0.4, 0], [0, 8.0]]
      beta: [[1.0, 0], [0, 20.0]]
    thinning:
      num_exp: 500
      num_sample: 100
      over_sample_rate: 1.5
      dtime_max: 5

  trainer_config:
    stage: test

H2expi :
  data_loading_specs:
    batch_size: 128
    num_workers: 1
    
  model_config:
    model_id: HawkesModel
    specs:
      mu: [1, 1]
      alpha: [[0.7, 0], [0, 1.5]]
      beta: [[1.0, 0], [0,5.0]]
    thinning:
      num_exp: 500
      num_sample: 100
      over_sample_rate: 1.5
      dtime_max: 5

  trainer_config:
    stage: test
  
H2expc :
  data_loading_specs:
    batch_size: 128
    num_workers: 1
    
  model_config:
    model_id: HawkesModel
    specs:
      mu: [1, 1]
      alpha: [[0.5, 0.9], [0.5, 2.0]]
      beta: [[1.0, 3.0], [2.0,5.0]]
    thinning:
      num_exp: 500
      num_sample: 100
      over_sample_rate: 1.5
      dtime_max: 5

  trainer_config:
    stage: test


NHP_test:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: NHP
    specs:
      hidden_size: 64
      time_emb_size: 16
      num_layers: 2
    thinning:
      num_exp: 500
      over_sample_rate: 1.5
      dtime_max: 5
    base_config:
      lr: 0.001
      lr_scheduler: True

  trainer_config:
    stage: test

RMTPP_test:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: RMTPP
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
    base_config:
      lr: 0.001
      lr_scheduler: True

  trainer_config:
    stage: test
    max_epochs: 100
    val_freq: 10
    logger_config:
      type: tensorboard
      name: logs

AttNHP_test:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: AttNHP
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 1
      num_heads: 2
    thinning:
      num_exp: 500
      over_sample_rate: 1.5
      dtime_max: 5
    base_config:
      lr: 0.001
      lr_scheduler: True

  trainer_config:
    stage: test
    max_epochs: 100
    val_freq: 10
    logger_config:
      type: tensorboard
      name: logs

SAHP_test:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: SAHP
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
      num_heads: 2
    base_config:
      lr: 0.001
      lr_scheduler: True
    thinning:
      num_exp: 500
      over_sample_rate: 1.5
      dtime_max: 5

  trainer_config:
    stage: test
    max_epochs: 100
    val_freq: 10
    logger_config:
      type: tensorboard
      name: logs

THP_test:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: THP
    specs:
      hidden_size: 64
      time_emb_size: 16
      num_layers: 2
      num_heads: 2
    thinning:
      num_exp: 500
      over_sample_rate: 1.5
      dtime_max: 5
    base_config:
      lr: 0.001
      lr_scheduler: True

  trainer_config:
    stage: test
    max_epochs: 100
    val_freq: 10
    logger_config:
      type: tensorboard
      name: logs

FullyNN_test:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: FullyNN
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
    thinning:
      num_exp: 500
      over_sample_rate: 1.5
      dtime_max: 5
    base_config:
      lr: 0.001
      lr_scheduler: True

  trainer_config:
    stage: test
    max_epochs: 100
    val_freq: 10
    logger_config:
      type: tensorboard
      name: logs

IntensityFree_test:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: IntensityFree
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
    thinning:
      num_exp: 500
      over_sample_rate: 1.5
      dtime_max: 5
    base_config:
      lr: 0.001
      lr_scheduler: True

  trainer_config:
    stage: test
    max_epochs: 100
    val_freq: 10
    logger_config:
      type: tensorboard
      name: logs

ODETPP_test:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: ODETPP
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
    thinning:
      num_exp: 500
      over_sample_rate: 1.5
      dtime_max: 5
    base_config:
      lr: 0.001
      lr_scheduler: True

  trainer_config:
    stage: test
    max_epochs: 100
    val_freq: 10
    logger_config:
      type: tensorboard
      name: logs