_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
            "2":
                - 1
                - 9
                - 49
                - 51
                - 55
                - 103
            "3":
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
lr:
    value: 0.01
lr_scheduler:
    value: true
max_epochs:
    value: 200
model_config:
    value: '{''rnn_type'': ''LSTM'', ''hidden_size'': 64, ''time_emb_size'': 16, ''num_layers'': 2, ''sharing_param_layer'': False, ''loss_integral_num_sample_per_step'': 20, ''dropout_rate'': 0.0, ''use_ln'': False, ''thinning'': {''num_seq'': 10, ''num_sample'': 1, ''num_exp'': 500, ''look_ahead_time'': 10, ''patience_counter'': 5, ''over_sample_rate'': 5, ''num_samples_boundary'': 5, ''dtime_max'': 5, ''num_step_gen'': 1}, ''num_event_types_pad'': None, ''num_event_types'': None, ''event_pad_index'': None, ''model_id'': ''NHP'', ''pretrained_model_dir'': None, ''gpu'': -1, ''model_specs'': {}}'
num_event_types:
    value: 10
