data: 
  test:
    data_format: json
    train_dir: NzoCs/test_dataset
    valid_dir: NzoCs/test_dataset
    test_dir: NzoCs/test_dataset
    data_specs:
      num_event_types: 2
      pad_token_id: 2
      padding_side: left

NHP:

  data_loading_specs:
    batch_size: 64
    num_workers: 4
    
  model_config:
    model_id: NHP
    specs:
      hidden_size: 64
      time_emb_size: 16
      num_layers: 2
    thinning:
      num_exp: 10 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      over_sample_rate: 1.5
      dtime_max: 5
      num_sample: 30
    base_config:
      lr: 0.001
      lr_scheduler: True
    simulation_config:
      start_time: 10
      end_time: 100
      max_sim_events : 50

  trainer_config:
    
    max_epochs: 5
    val_freq: 10
    accumulate_grad_batches: 1
    patience: 5
    logger_config:
      type: tensorboard
      name: logs

RMTPP:

  data_loading_specs:
    batch_size: 128
    num_workers: 4
    
  model_config:
    model_id: RMTPP
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
    thinning:
      num_exp: 10 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      over_sample_rate: 1.5
      dtime_max: 5
      num_sample: 30
    base_config:
      lr: 0.001
      lr_scheduler: True
    simulation_config:
      start_time: 10
      end_time: 100
      max_sim_events : 50

  trainer_config:
    max_epochs: 5
    val_freq: 10
    accumulate_grad_batches: 1
    patience: 5
    logger_config:
      type: tensorboard
      name: logs

AttNHP:

  data_loading_specs:
    batch_size: 64
    num_workers: 4
    
  model_config:
    model_id: AttNHP
    specs:
      hidden_size: 16
      time_emb_size: 16
      num_layers: 1
      num_heads: 2
    thinning:
      num_exp: 10 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      over_sample_rate: 1.5
      dtime_max: 5
      num_sample: 30
    base_config:
      lr: 0.001
      lr_scheduler: True
    simulation_config:
      start_time: 10
      end_time: 100
      max_sim_events : 50

  trainer_config:
    max_epochs: 5
    val_freq: 10
    accumulate_grad_batches: 2
    patience: 5
    logger_config:
      type: tensorboard
      name: logs

SAHP:

  data_loading_specs:
    batch_size: 64
    num_workers: 4
    
  model_config:
    model_id: SAHP
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
      num_heads: 2
    base_config:
      lr: 0.001
      lr_scheduler: True
    thinning:
      num_exp: 10 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      over_sample_rate: 1.5
      dtime_max: 5
      num_sample: 30
    simulation_config:
      start_time: 10
      end_time: 100
      max_sim_events : 50

  trainer_config:
    max_epochs: 5
    val_freq: 10
    accumulate_grad_batches: 2
    patience: 5
    logger_config:
      type: tensorboard
      name: logs

THP:

  data_loading_specs:
    batch_size: 64
    num_workers: 4
    
  model_config:
    model_id: THP
    specs:
      hidden_size: 64
      time_emb_size: 16
      num_layers: 2
      num_heads: 2
    base_config:
      lr: 0.001
      lr_scheduler: True
    thinning:
      num_exp: 10
      over_sample_rate: 1.5
      dtime_max: 5
      num_sample: 30
    simulation_config:
      start_time: 10
      end_time: 100
      max_sim_events : 50

  trainer_config:
    max_epochs: 5
    val_freq: 10
    accumulate_grad_batches: 2
    patience: 5
    logger_config:
      type: tensorboard
      name: logs

FullyNN:

  data_loading_specs:
    batch_size: 64
    num_workers: 4
    
  model_config:
    model_id: FullyNN
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
    base_config:
      lr: 0.001
      lr_scheduler: True
    thinning:
      num_exp: 100 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      over_sample_rate: 1.5
      dtime_max: 5
      num_sample: 60
    simulation_config:
      start_time: 10
      end_time: 100
      max_sim_events : 50
      
  trainer_config:
    max_epochs: 5
    val_freq: 10
    accumulate_grad_batches: 1
    patience: 5
    logger_config:
      type: tensorboard
      name: logs

IntensityFree:

  data_loading_specs:
    batch_size: 256
    num_workers: 4
    
  model_config:
    model_id: IntensityFree
    specs:
      hidden_size: 32
      time_emb_size: 16
      num_layers: 2
    thinning:
      num_exp: 10 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      over_sample_rate: 1.5
      dtime_max: 5
      num_sample: 30
    base_config:
      lr: 0.001
      lr_scheduler: True
    simulation_config:
      start_time: 10
      end_time: 100
      max_sim_events : 50
      
  trainer_config:
    max_epochs: 5
    val_freq: 10
    accumulate_grad_batches: 1
    patience: 5
    logger_config:
      type: tensorboard
      name: logs
