pipeline_config_id: runner_config

data:

  taxi:
    data_format: json
    train_dir:  easytpp/taxi  # ./data/taxi/train.json
    valid_dir:  easytpp/taxi # ./data/taxi/dev.json
    test_dir:  easytpp/taxi # ./data/taxi/test.json
    data_specs:
      num_event_types: 10
      pad_token_id: 10
      padding_side: right
      
  H1DLHP :
    data_format: json
    train_dir : ../synthetic_data_gen/data/H1DLHP/train.json
    valid_dir: ../synthetic_data_gen/data/H1DLHP/dev.json
    test_dir:   ../synthetic_data_gen/data/H1DLHP/test.json
    data_specs:
      num_event_types: 1
      pad_token_id: 1
      padding_side: left
      truncation_side: left

  hawkes1 :
    data_format: json
    train_dir : ../synthetic_data_gen/data/hawkes1/train.json
    valid_dir: ../synthetic_data_gen/data/hawkes1/dev.json
    test_dir:   ../synthetic_data_gen/data/hawkes1/test.json
    data_specs:
      num_event_types: 1
      pad_token_id: 1
      padding_side: left
      truncation_side: left
  
  self_correcting :
    data_format: json
    train_dir : ../synthetic_data_gen/data/self_correcting/train.json
    valid_dir: ../synthetic_data_gen/data/self_correcting/dev.json
    test_dir:   ../synthetic_data_gen/data/self_correcting/test.json
    data_specs:
      num_event_types: 1
      pad_token_id: 1
      padding_side: left
      truncation_side: left


NHP_hawkes1_train :

  data_loading_specs : 
    batch_size: 256
    num_workers: 4

  model_config:
    model_id : NHP
    hidden_size : 16
    loss_integral_num_sample_per_step: 20
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1
      
  trainer_config : 
    stage : train
    dataset_id: hawkes1
    max_epochs : 400
    val_freq : 5
    lr : 0.01
    lr_scheduler : True
    num_workers : 4
    save_dir : ./NHP/hawkes1/exp1 #A remplir pour pouvoir repartir d'un point de sauvegarde
    logger_type : tensorboard
    logger_config :
      name : tensorboard_logs

NHP_self_correcting_train :
  
    data_loading_specs : 
      batch_size: 256
  
    model_config:
      model_id : NHP
      hidden_size : 16
      loss_integral_num_sample_per_step: 20
      thinning:
        num_seq: 10
        num_sample: 1
        num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
        look_ahead_time: 10
        patience_counter: 5 # the maximum iteration used in adaptive thinning
        over_sample_rate: 5
        num_samples_boundary: 5
        dtime_max: 5
        num_step_gen: 1
        
    trainer_config : 
      stage : train
      dataset_id: self_correcting
      max_epochs : 400
      val_freq : 5
      lr : 0.01
      lr_scheduler : True
      save_dir : ./NHP/self_correcting/exp1
      logger_type : tensorboard
      logger_config :
        name : tensorboard_logs

RMTPP_self_correcting_train :
  
    
    data_loading_specs : 
      batch_size: 256
  
    model_config:
      model_id : RMTPP
      hidden_size : 16
      loss_integral_num_sample_per_step: 20
      simulation : 
        start_time : 200
        end_time : 300
      thinning:
        num_seq: 10
        num_sample: 1
        num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
        look_ahead_time: 10
        patience_counter: 5 # the maximum iteration used in adaptive thinning
        over_sample_rate: 5
        num_samples_boundary: 5
        dtime_max: 5
        num_step_gen: 1
        
    trainer_config : 
      stage : train
      dataset_id: self_correcting
      max_epochs : 400
      val_freq : 5
      lr : 0.01
      lr_scheduler : True
      save_dir : ./RMTPP/self_correcting/exp1
      logger_type : tensorboard
      logger_config :
        name : tensorboard_logs

RMTPP_hawkes1_train :

  data_loading_specs : 
    batch_size: 256

  model_config:
    model_id : RMTPP
    hidden_size : 16
    loss_integral_num_sample_per_step: 20
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1
      
  trainer_config : 
    stage : train
    dataset_id: hawkes1
    max_epochs : 400
    val_freq : 5
    lr : 0.01
    lr_scheduler : True
    save_dir : ./RMTPP/hawkes1/trained_models/exp1
    logger_type : tensorboard
    logger_config :
      name : tensorboard_logs