pipeline_config_id : syn_gen_config

H1DLHP : 
  model_id : Hawkes
  save_dir : ./data/H1expDLHP
  num_mark : 1
  start_time : 0
  end_time : 100
  test_end_time : 100
  num_batch : 10
  batch_size : 1
  sampler_config :
    num_samples : 1
    num_exp : 500
    num_samples_boundary : 30
    over_sample_rate : 1.2
    dtime_max : 5
    patience_counter : 100
  model_config : 
    mu : 0.3
    alpha : 0.65
    decay : 0.8

hawkes1 :
  model_id : Hawkes
  save_dir : ./data/hawkes1_perso
  num_mark : 1
  start_time : 100
  end_time : 200
  test_end_time : 250
  num_batch : 10
  batch_size : 8
  sampler_config :
    num_samples : 1
    num_exp : 500
    num_samples_boundary : 30
    over_sample_rate : 1
    dtime_max : 15
    patience_counter : 100
  model_config : 
    mu : 0.2
    alpha : 0.8
    decay : 1

H2expDLHP :
    model_id : Hawkes
    save_dir : ./data/H2expDLHP
    num_mark : 2
    start_time : 100
    end_time : 200
    test_end_time : 250
    num_batch : 6
    batch_size : 4
    sampler_config :
      num_samples : 1
      num_exp : 200
      num_samples_boundary : 30
      over_sample_rate : 1.2
      dtime_max : 5
      patience_counter : 100
    model_config :
      mu : [0.2,0.3]
      alpha : [[0.6,0.7],[0.4,0.6]]
      decay : [[1,0.8],[0.7,0.9]]

H2expi:
  model_id : Hawkes
  save_dir : ./data/H2expi
  num_mark : 2
  start_time : 0
  end_time : 50
  test_end_time : 100
  num_batch : 6
  batch_size : 4
  sampler_config :
    num_samples : 1
    num_exp : 500
    num_samples_boundary : 30
    over_sample_rate : 1.2
    dtime_max : 2
    patience_counter : 100
  model_config :
    mu : [1,1]
    alpha : [[0.7,0],[0,1.5]]
    decay : [[1,0],[0,5]]

H2expc :
  model_id : Hawkes
  save_dir : ./data/H2expc
  num_mark : 2
  start_time : 100
  end_time : 200
  test_end_time : 250
  num_batch : 190
  batch_size : 256
  sampler_config :
    num_samples : 1
    num_exp : 200
    num_samples_boundary : 30
    over_sample_rate : 1.2
    dtime_max : 5
    patience_counter : 100
  model_config :
    mu : [1,1]
    alpha : [[0.5,0.9],[0.5,2]]
    decay : [[1,3],[2,5]]