pipeline_config_id: data_config

H2expi :
  data_format: json
  train_dir: NzoCs/H2expi-temporal-dataset 
  valid_dir: NzoCs/H2expi-temporal-dataset
  test_dir:  NzoCs/H2expi-temporal-dataset
  data_specs:
    num_event_types: 2
  
H2expc :
  data_format: json
  train_dir: NzoCs/H2expc-temporal-dataset 
  valid_dir: NzoCs/H2expc-temporal-dataset
  test_dir:  NzoCs/H2expc-temporal-dataset
  data_specs:
    num_event_types: 2

H2expc_test :
  data_format: json
  train_dir: NzoCs/H2expc_test-temporal-dataset
  valid_dir: NzoCs/H2expc_test-temporal-dataset
  test_dir:  NzoCs/H2expc_test-temporal-dataset
  data_specs:
    num_event_types: 2

hawkes1 :
  data_format: json
  train_dir: NzoCs/hawkes1-temporal-dataset
  valid_dir: NzoCs/hawkes1-temporal-dataset
  test_dir:  NzoCs/hawkes1-temporal-dataset
  data_specs:
    num_event_types: 1

hawkes2 :
  data_format: json
  train_dir: NzoCs/hawkes2_-temporal-dataset
  valid_dir: NzoCs/hawkes2_-temporal-dataset
  test_dir:  NzoCs/hawkes2_-temporal-dataset
  data_specs:
    num_event_types: 2

self_correcting : 
  data_format: json
  train_dir: NzoCs/self_correcting-temporal-dataset
  valid_dir: NzoCs/self_correcting-temporal-dataset
  test_dir:  NzoCs/self_correcting-temporal-dataset
  data_specs:
    num_event_types: 1

taxi :
  data_format: json
  train_dir:  easytpp/taxi  
  valid_dir:  easytpp/taxi 
  test_dir:  easytpp/taxi 
  data_specs:
    num_event_types: 10