pipeline_config_id: evaluation_config
# Compare H2expi vs H2expc
H2expi_vs_H2expc:

  label_data_config:
    data_format: json
    train_dir: NzoCs/H2expi-temporal-dataset
    valid_dir: NzoCs/H2expi-temporal-dataset
    test_dir: NzoCs/H2expi-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: NzoCs/H2expc-temporal-dataset
    valid_dir: NzoCs/H2expc-temporal-dataset
    test_dir: NzoCs/H2expc-temporal-dataset
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./H2expi_vs_H2expc

NHP_hawkes1:

  label_data_config:
    data_format: json
    train_dir: NzoCs/hawkes1-temporal-dataset
    valid_dir: NzoCs/hawkes1-temporal-dataset
    test_dir: NzoCs/hawkes1-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/NHP/hawkes1/simulations.json
    test_dir: ../simulation/simul/NHP/hawkes1/simulations.json
    valid_dir: ../simulation/simul/NHP/hawkes1/simulations.json
  data_specs:
    num_event_types: 1
    
  label_split: test
  pred_split: test
  output_dir: ./NHP_hawkes1

AttNHP_test:

  label_data_config:
    data_format: json
    train_dir: NzoCs/test-temporal-dataset
    valid_dir: NzoCs/test-temporal-dataset
    test_dir: NzoCs/test-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/AttNHP/test/simulations.json
    test_dir: ../simulation/simul/AttNHP/test/simulations.json
    valid_dir: ../simulation/simul/AttNHP/test/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./AttNHP_test

NHP_hawkes2:

  label_data_config:
    data_format: json
    train_dir: NzoCs/hawkes2-temporal-dataset
    valid_dir: NzoCs/hawkes2-temporal-dataset
    test_dir: NzoCs/hawkes2-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/NHP/hawkes2/train
    valid_dir: ../simulation/NHP/hawkes2/valid
    test_dir: ../simulation/NHP/hawkes2/test
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: 
  output_dir: ./H2expi_vs_H2expc