pipeline_config_id: evaluation_config

NHP_hawkes1:

  label_data_config:
    data_format: json
    train_dir: NzoCs/hawkes1-temporal-dataset
    valid_dir: NzoCs/hawkes1-temporal-dataset
    test_dir: NzoCs/hawkes1-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/NHP/hawkes1/simulations.json
    test_dir: ../simulation/simul/NHP/hawkes1/simulations.json
    valid_dir: ../simulation/simul/NHP/hawkes1/simulations.json
  data_specs:
    num_event_types: 1
    
  label_split: test
  pred_split: test
  output_dir: ./NHP_hawkes1

THP_hawkes1:

  label_data_config:
    data_format: json
    train_dir: NzoCs/hawkes1-temporal-dataset
    valid_dir: NzoCs/hawkes1-temporal-dataset
    test_dir: NzoCs/hawkes1-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/THP/hawkes1/simulations.json
    test_dir: ../simulation/simul/THP/hawkes1/simulations.json
    valid_dir: ../simulation/simul/THP/hawkes1/simulations.json
  data_specs:
    num_event_types: 1
    
  label_split: test
  pred_split: test
  output_dir: ./THP_hawkes1

AttNHP_test:

  label_data_config:
    data_format: json
    train_dir: NzoCs/test-temporal-dataset
    valid_dir: NzoCs/test-temporal-dataset
    test_dir: NzoCs/test-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/AttNHP/test/simulations.json
    test_dir: ../simulation/simul/AttNHP/test/simulations.json
    valid_dir: ../simulation/simul/AttNHP/test/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./AttNHP_test

NHP_hawkes2:

  label_data_config:
    data_format: json
    train_dir: NzoCs/hawkes2_-temporal-dataset
    valid_dir: NzoCs/hawkes2_-temporal-dataset
    test_dir: NzoCs/hawkes2_-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/NHP/hawkes2_/simulations.json
    valid_dir: ../simulation/simul/NHP/hawkes2_/simulations.json
    test_dir: ../simulation/simul/NHP/hawkes2_/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./NHP_hawkes2

THP_hawkes2:

  label_data_config:
    data_format: json
    train_dir: NzoCs/hawkes2_-temporal-dataset
    valid_dir: NzoCs/hawkes2_-temporal-dataset
    test_dir: NzoCs/hawkes2_-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/THP/hawkes2_/simulations.json
    valid_dir: ../simulation/simul/THP/hawkes2_/simulations.json
    test_dir: ../simulation/simul/THP/hawkes2_/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./THP_hawkes2

NHP_sc:

  label_data_config:
    data_format: json
    train_dir: NzoCs/self_coorecting-temporal-dataset
    valid_dir: NzoCs/self_correcting-temporal-dataset
    test_dir: NzoCs/self_correcting-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/NHP/self_correcting/simulations.json
    valid_dir: ../simulation/simul/NHP/self_correcting/simulations.json
    test_dir: ../simulation/simul/NHP/self_correcting/simulations.json
  data_specs:
    num_event_types: 1
    
  label_split: test
  pred_split: test
  output_dir: ./NHP_sc

NHP_H2expi:

  label_data_config:
    data_format: json
    train_dir: NzoCs/H2expi-temporal-dataset
    valid_dir: NzoCs/H2expi-temporal-dataset
    test_dir: NzoCs/H2expi-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/NHP/H2expi/simulations.json
    valid_dir: ../simulation/simul/NHP/H2expi/simulations.json
    test_dir: ../simulation/simul/NHP/H2expi/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./NHP_H2expi

RMTPP_hawkes2_:

  label_data_config:
    data_format: json
    train_dir: NzoCs/H2expi-temporal-dataset
    valid_dir: NzoCs/H2expi-temporal-dataset
    test_dir: NzoCs/H2expi-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/RMTPP/hawkes2_/simulations.json
    valid_dir: ../simulation/simul/RMTPP/hawkes2_/simulations.json
    test_dir: ../simulation/simul/RMTPP/hawkes2_/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./RMTPP_hawkes2

THP_H2expi:

  label_data_config:
    data_format: json
    train_dir: NzoCs/H2expi-temporal-dataset
    valid_dir: NzoCs/H2expi-temporal-dataset
    test_dir: NzoCs/H2expi-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/THP/H2expi/simulations.json
    valid_dir: ../simulation/simul/THP/H2expi/simulations.json
    test_dir: ../simulation/simul/THP/H2expi/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./THP_H2expi

THP_H2expc:

  label_data_config:
    data_format: json
    train_dir: NzoCs/H2expc-temporal-dataset
    valid_dir: NzoCs/H2expc-temporal-dataset
    test_dir: NzoCs/H2expc-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/THP/H2expc/simulations.json
    valid_dir: ../simulation/simul/THP/H2expc/simulations.json
    test_dir: ../simulation/simul/THP/H2expc/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./THP_H2expc

NHP_H2expc:

  label_data_config:
    data_format: json
    train_dir: NzoCs/H2expc-temporal-dataset
    valid_dir: NzoCs/H2expc-temporal-dataset
    test_dir: NzoCs/H2expc-temporal-dataset

  pred_data_config:
    data_format: json
    train_dir: ../simulation/simul/NHP/H2expc/simulations.json
    valid_dir: ../simulation/simul/NHP/H2expc/simulations.json
    test_dir: ../simulation/simul/NHP/H2expc/simulations.json
  data_specs:
    num_event_types: 2
    
  label_split: test
  pred_split: test
  output_dir: ./NHP_H2expc